Getting started with numpy;
why should you use numpy for computation instead of regular python list?
1. numpy array have the speed advantage.
2. A lot of build in computational function to choose from.
3. multidimensionality is easy with numpy.

In [1]:
import numpy as np;

In [2]:
#creating a numpy array, 1 dimension;
score = [1, 2, 3, 4, 5]
score = np.array(score)
score

array([1, 2, 3, 4, 5])

In [3]:
#let create a 2 dimensional array using range() to generate the 1 dimensional array;
matrix = np.array([range(i, i + 3) for i in [2, 4, 6]])
matrix


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
#creating an array from scratch;
zero = np.zeros(5, dtype=int)
zeros = np.zeros((4, 3), dtype=float)
print(" 1 dimension zero:", zero)
print("2 dimension zeros:", zeros)

 1 dimension zero: [0 0 0 0 0]
2 dimension zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# creating an array with arange()
arr = np.arange(5, 45, 5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [32]:
# create a matrix of random integer;
matrix = np.random.randint(1, 6, (3,3))
matrix

array([[5, 2, 4],
       [1, 1, 4],
       [3, 5, 4]])

In [7]:
# create a 3 dimensional array;
three = np.random.randint(20, size=(5, 4, 3))
three

array([[[ 1, 19, 15],
        [17, 15,  4],
        [12,  0, 13],
        [13, 10,  1]],

       [[12,  8,  4],
        [16, 13, 15],
        [15,  6, 14],
        [ 5,  8,  7]],

       [[ 0, 16, 12],
        [ 6, 11, 12],
        [ 8, 17,  4],
        [ 7,  2,  8]],

       [[ 7, 14, 15],
        [ 9, 18,  5],
        [12, 15, 18],
        [ 8, 10,  5]],

       [[ 2, 19, 18],
        [ 7,  6,  3],
        [ 1,  5, 19],
        [13,  1, 11]]])

In [8]:
# lets get the attributes of the 3 dimension array;
print("dimension: ", three.ndim)
print("shape:", three.shape)
print("size: ", three.size)


dimension:  3
shape: (5, 4, 3)
size:  60


In [9]:
# selecting items in numpy array is just like in regular python list;
x = np.array([1, 2, 4, 6, 7 ,9])
x[4]

7

In [33]:
# create a 3 dimensional array;
three = np.random.randint(20, size=(5, 4, 3))
three

array([[[ 4,  5, 11],
        [14, 11,  1],
        [19,  3, 19],
        [ 4,  8,  3]],

       [[16, 14,  9],
        [12, 19, 11],
        [ 4, 18, 13],
        [11,  5, 17]],

       [[19, 14, 14],
        [ 3,  6, 16],
        [ 3,  7,  2],
        [16,  4,  8]],

       [[17,  6,  3],
        [11,  8,  4],
        [ 5,  8,  6],
        [10,  6,  3]],

       [[ 1, 14,  6],
        [10, 16,  5],
        [ 3, 10, 17],
        [15,  3, 16]]])

In [35]:
# selection in multidimensional array;
three[0, 0, 0] # this will give us 4

4

In [36]:
# slicing a multidimensional array;
# create a 2 dimensional array from three;
x3 = three[0, :,]
x3

array([[ 4,  5, 11],
       [14, 11,  1],
       [19,  3, 19],
       [ 4,  8,  3]])

In [37]:
# slice out the first column from x3;
x3[:, 0]

array([ 4, 14, 19,  4])

In [39]:
# creating copy of x3 rather than a view;
# a copy don't change its parent array;
x4 = x3[:, 0].copy()
print("x4 before modification:", x4)
x4[1] = 7
print("x4 after modification:", x4)
print("x3 remain the same:", x3)

x4 before modification: [ 4 14 19  4]
x4 after modification: [ 4  7 19  4]
x3 remain the same: [[ 4  5 11]
 [14 11  1]
 [19  3 19]
 [ 4  8  3]]


In [40]:
# reshaping an array;
x = np.arange(20)
print("plain x: ", x)
print("reshaped x: ", x.reshape((5, 4)))

plain x:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshaped x:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [41]:
# array concatenation and splitting;
x = np.array([2, 4, 6, 8])
y = np.array([3, 6, 9, 12])
np.concatenate([x, y])

array([ 2,  4,  6,  8,  3,  6,  9, 12])

In [42]:
# concatenation by stacking

stack = np.vstack([x, y])
stack

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [17]:
# splitting arrays;
# spliting horizontally;
np.hsplit(stack, [2])

[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [18]:
# computation with numpy using ufunc;
zero = np.zeros((3,3))
zero = zero + 5
zero

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [19]:
# exponential computation with numpy
np.power(2, zero)

array([[32., 32., 32.],
       [32., 32., 32.],
       [32., 32., 32.]])

In [20]:
# adding zero along the 0 axis;
np.add.reduce(zero)

array([15., 15., 15.])

In [21]:
# playing with aggregation;
x = np.array([1, 2, 3, 4, 5])
np.sum(x)

15

In [22]:
np.min(x)

1

In [23]:
np.max(x)

5

In [24]:
# multidimensional aggregation;
y = np.arange(20).reshape(5, 4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
np.sum(y)

190

In [26]:
# summing along the row axis;
y.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [27]:
# min along the column axis;
y.min(axis=0)

array([0, 1, 2, 3])

In [44]:
# broadcasting in numpy;
# this is how numpy handle computation on array of different shape;
one = np.ones(2)
two = np.ones((2, 2))
print("one :", one)     
print("two :", two)

one : [1. 1.]
two : [[1. 1.]
 [1. 1.]]


In [46]:
"""
one and two will add up even though they 
are not if the same shape;
this is possible through broadcasting
"""
one + two

array([[2., 2.],
       [2., 2.]])

In [47]:
# mask in numpy, passing condition as index;
x = np.array([2, 6, 9, 5, 1, 8])
x[x >= 6]

array([6, 9, 8])

In [48]:
# fancy indexing, using array as index;
x[[1, 3, 5]]

array([6, 5, 8])

In [49]:
# combining indexing in numpy;
x = np.random.randint(15, size=(4, 3, 3))
x

array([[[ 6,  9,  2],
        [ 5, 10,  9],
        [ 6, 11,  3]],

       [[ 8,  4,  7],
        [11,  6, 11],
        [ 1,  0,  5]],

       [[11,  0,  6],
        [11,  8, 13],
        [10,  9,  8]],

       [[12, 12, 13],
        [ 2,  0,  0],
        [ 0,  0, 14]]])

In [50]:
"""
create another multidimensional array 
of 2 item from x with combined indexing;
"""
x[:, :, [1,2]]

array([[[ 9,  2],
        [10,  9],
        [11,  3]],

       [[ 4,  7],
        [ 6, 11],
        [ 0,  5]],

       [[ 0,  6],
        [ 8, 13],
        [ 9,  8]],

       [[12, 13],
        [ 0,  0],
        [ 0, 14]]])

In [51]:
# sorting arrays in numpy;
x = np.random.randint(10, size=(4,4))
np.sort(x) # sorting along the x axis

array([[3, 6, 7, 8],
       [0, 1, 2, 8],
       [3, 3, 6, 8],
       [2, 8, 9, 9]])

In [52]:
# lets. sort x along the y axis;
np.sort(x, axis=0)

array([[2, 0, 6, 1],
       [2, 3, 8, 3],
       [3, 7, 8, 8],
       [6, 9, 8, 9]])

In [53]:
"""
structured array in numpy;
creating a structure array with numpy;
it is good way for stroing related data
"""
data = np.zeros(5, dtype=([('country', 'S10'), ('founded', 'i4'), ('population', 'i4')]))

In [55]:
data_rec = data.view(np.recarray)

In [56]:
data_rec.country = np.array(["nigeria", "ghana",
         "isreal", "france", "spain"])
data_rec.founded = np.array([1990, 1880, 1770,
                   1660, 1550])
data_rec.population = np.array([3000, 4000, 5000,
                6000, 7000])

In [59]:
data_rec.country

array([b'nigeria', b'ghana', b'isreal', b'france', b'spain'], dtype='|S10')

In [57]:
data_rec[0]

(b'nigeria', 1990, 3000)

In [58]:
data_rec.country[0]

b'nigeria'