why should you use pandas?
its make analysis easy in comparison to numpy;
it is build on numpy, so also have the speed;
lower level coding abstraction;

In [1]:
import numpy as np;
import pandas as pd

In [2]:
"""
Series, the most basic data structure in 
pandas;
lets create a series with pd.Series
"""
data = pd.Series(range(10, 100, 10))
# pandas 
data

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [3]:
# getting values in a Series;
data.values

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
# we can also get index in series like below
data.index

RangeIndex(start=0, stop=9, step=1)

In [5]:
# using explicit string index for series;
names = pd.Series(["john", "kate", "sule", 
                "eniola", "alicia"], index=
                  ["a", "b", "c", "d", "e"])

In [6]:
# getting name with implicit index;
names["c"]

'sule'

In [7]:
# getting name with implicit index;
names[2]

'sule'

In [8]:
dic = {
    "a": "john",
    "b": "kate",
    "c": "sule",
    "d": "eniola",
    "e": "alicia",
    }

In [9]:
# creating series from python dictionary;
names = pd.Series(dic)
names

a      john
b      kate
c      sule
d    eniola
e    alicia
dtype: object

In [10]:
# let slice names;
names["b" : "d"]

b      kate
c      sule
d    eniola
dtype: object

In [11]:
# multidimensionality with pandas dataframe; 
# creating a dataframe with two column;

population = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}
area = {
    'California': 423967, 
    'Texas': 695662, 
    'New York': 141297,
    'Florida': 170312, 
    'Illinois': 149995
}

data = pd.DataFrame({"population": population, 
                   "area": area}) 
data # cool isn't it

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [12]:
# getting the index of our data
data.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [13]:
# getting the column name in the data
data.columns

Index(['population', 'area'], dtype='object')

In [14]:
# we can get individual column as a series
data["population"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [16]:
# let add a new column in to the data;
# column name will be density;
data["density"] = data.population/data.area
data

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [21]:
# lets view the dimensionality of the dataframe;
# it have a shape of (5, 3)
data.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [22]:
# lets select one of the inner arrays;
data.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [23]:
# lets view the data from another angle;
# it will be cool
data.T

California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01

In [24]:
# selection and slicing  in pandas dataframe;
# you can use either the implicit or explicit imdex.       
data.iloc[3:, 0:2]

population    area
Florida     19552860  170312
Illinois    12882135  149995

In [25]:
# slicing with explicit index
data.loc["Florida":, "population":"area"]

population    area
Florida     19552860  170312
Illinois    12882135  149995

In [26]:
# using a combine indexing in pandas;
data.loc[data.density<100, ["population",
                         "area"]] 

population    area
California    38332521  423967
Texas         26448193  695662
Illinois      12882135  149995

In [27]:
# modifing dataframe with index;
data.loc[data.density<100, "density"] = 100
data

population    area     density
California    38332521  423967  100.000000
Texas         26448193  695662  100.000000
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995  100.000000

In [28]:
# using ufunc with pandas, its simple;
no = pd.Series([0, 2, 4, 7, 8, 3, 6])
np.sum(no)

30

In [29]:
# another example of ufunc in pandas;
x = np.random.randint(2, 9, size=(3,3))
y = pd.DataFrame(x, columns=["first", "second",
                         "third"])
y

first  second  third
0      8       5      2
1      5       3      7
2      6       7      7

In [30]:
# let's find the min along the y axis;
np.min(y, axis=0)

first     5
second    3
third     2
dtype: int64

In [31]:
# let's find the max aloxng the x axis;
np.max(y, axis=1)

0    8
1    7
2    7
dtype: int64

In [32]:
# computation on two dataframes of different structure.                   
x = pd.DataFrame(np.random.randint(5, size=
                      (3, 2)), 
                columns= ["a", "b"])
y = pd.DataFrame(np.random.randint(3,9, size=
                      (4, 5)),
                columns= ["a", "b", "c", "d",
                          "e"])



In [33]:
print(x)
print(y)

   a  b
0  1  4
1  4  0
2  4  0
   a  b  c  d  e
0  6  4  4  6  6
1  7  4  4  4  8
2  8  8  5  7  4
3  8  6  7  5  7


In [34]:
"""
like broadcasting in numpy, pandas use 
index aligning;
"""
x + y

a    b   c   d   e
0   7.0  8.0 NaN NaN NaN
1  11.0  4.0 NaN NaN NaN
2  12.0  8.0 NaN NaN NaN
3   NaN  NaN NaN NaN NaN

In [35]:
"""
we can then fill in the null data
during computation like this;
"""
x.add(y, fill_value=0)

a    b    c    d    e
0   7.0  8.0  4.0  6.0  6.0
1  11.0  4.0  4.0  4.0  8.0
2  12.0  8.0  5.0  7.0  4.0
3   8.0  6.0  7.0  5.0  7.0

In [36]:
# working with none and nan in data with pandas;.   
x = pd.Series([0, np.nan, 2, 3, 4, np.nan])
x

0    0.0
1    NaN
2    2.0
3    3.0
4    4.0
5    NaN
dtype: float64

In [37]:
# checking for nan value in x;
x.isnull() # this return boolean items

0    False
1     True
2    False
3    False
4    False
5     True
dtype: bool

In [38]:
# we can drop the nan in x like this;
x.dropna()

0    0.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [39]:
# we can even fill in value for the nan;
x.fillna(0)

0    0.0
1    0.0
2    2.0
3    3.0
4    4.0
5    0.0
dtype: float64

In [46]:
# introduction to hierarchy indexing;
# multidimensionality in pandas;
# let's create one using a dic;
data = {
    ('California', 2000): 33871648,
    ('California', 2010): 37253956,
    ('Texas', 2000): 20851820,
    ('Texas', 2010): 25145561,
    ('New York', 2000): 18976457,
    ('New York', 2010): 19378102}

data = pd.Series(data)
data.index.names = ["state", "year"]
data.columns= "population"

In [48]:
# data with sub-category is easy with hierarchy index.         ;
# let get the population of the states in 2010;
data[:, 2010]

state
California    37253956
Texas         25145561
New York      19378102
dtype: int64